version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
